package com.lanccj.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public void setFModuleid(java.lang.Integer fModuleid) {
		set("F_ModuleId", fModuleid);
	}

	public java.lang.Integer getFModuleid() {
		return get("F_ModuleId");
	}

	public void setFParentid(java.lang.Integer fParentid) {
		set("F_ParentId", fParentid);
	}

	public java.lang.Integer getFParentid() {
		return get("F_ParentId");
	}

	public void setFEncode(java.lang.String fEncode) {
		set("F_EnCode", fEncode);
	}

	public java.lang.String getFEncode() {
		return get("F_EnCode");
	}

	public void setFFullname(java.lang.String fFullname) {
		set("F_FullName", fFullname);
	}

	public java.lang.String getFFullname() {
		return get("F_FullName");
	}

	public void setFIcon(java.lang.String fIcon) {
		set("F_Icon", fIcon);
	}

	public java.lang.String getFIcon() {
		return get("F_Icon");
	}

	public void setFUrladdress(java.lang.String fUrladdress) {
		set("F_UrlAddress", fUrladdress);
	}

	public java.lang.String getFUrladdress() {
		return get("F_UrlAddress");
	}

	public void setFTarget(java.lang.String fTarget) {
		set("F_Target", fTarget);
	}

	public java.lang.String getFTarget() {
		return get("F_Target");
	}

	public void setFIsmenu(java.lang.String fIsmenu) {
		set("F_IsMenu", fIsmenu);
	}

	public java.lang.String getFIsmenu() {
		return get("F_IsMenu");
	}

	public void setFAllowexpand(java.lang.String fAllowexpand) {
		set("F_AllowExpand", fAllowexpand);
	}

	public java.lang.String getFAllowexpand() {
		return get("F_AllowExpand");
	}

	public void setFIspublic(java.lang.String fIspublic) {
		set("F_IsPublic", fIspublic);
	}

	public java.lang.String getFIspublic() {
		return get("F_IsPublic");
	}

	public void setFAllowedit(java.lang.String fAllowedit) {
		set("F_AllowEdit", fAllowedit);
	}

	public java.lang.String getFAllowedit() {
		return get("F_AllowEdit");
	}

	public void setFAllowdelete(java.lang.String fAllowdelete) {
		set("F_AllowDelete", fAllowdelete);
	}

	public java.lang.String getFAllowdelete() {
		return get("F_AllowDelete");
	}

	public void setFSortcode(java.lang.String fSortcode) {
		set("F_SortCode", fSortcode);
	}

	public java.lang.String getFSortcode() {
		return get("F_SortCode");
	}

	public void setFDeletemark(java.lang.String fDeletemark) {
		set("F_DeleteMark", fDeletemark);
	}

	public java.lang.String getFDeletemark() {
		return get("F_DeleteMark");
	}

	public void setFEnabledmark(java.lang.String fEnabledmark) {
		set("F_EnabledMark", fEnabledmark);
	}

	public java.lang.String getFEnabledmark() {
		return get("F_EnabledMark");
	}

	public void setFDescription(java.lang.String fDescription) {
		set("F_Description", fDescription);
	}

	public java.lang.String getFDescription() {
		return get("F_Description");
	}

	public void setFCreatedate(java.util.Date fCreatedate) {
		set("F_CreateDate", fCreatedate);
	}

	public java.util.Date getFCreatedate() {
		return get("F_CreateDate");
	}

	public void setFCreateuserid(java.lang.Integer fCreateuserid) {
		set("F_CreateUserId", fCreateuserid);
	}

	public java.lang.Integer getFCreateuserid() {
		return get("F_CreateUserId");
	}

	public void setFCreateusername(java.lang.String fCreateusername) {
		set("F_CreateUserName", fCreateusername);
	}

	public java.lang.String getFCreateusername() {
		return get("F_CreateUserName");
	}

	public void setFModifydate(java.util.Date fModifydate) {
		set("F_ModifyDate", fModifydate);
	}

	public java.util.Date getFModifydate() {
		return get("F_ModifyDate");
	}

	public void setFModifyuserid(java.lang.Integer fModifyuserid) {
		set("F_ModifyUserId", fModifyuserid);
	}

	public java.lang.Integer getFModifyuserid() {
		return get("F_ModifyUserId");
	}

	public void setFModifyusername(java.lang.String fModifyusername) {
		set("F_ModifyUserName", fModifyusername);
	}

	public java.lang.String getFModifyusername() {
		return get("F_ModifyUserName");
	}

	public void setFTest(java.lang.String fTest) {
		set("F_Test", fTest);
	}

	public java.lang.String getFTest() {
		return get("F_Test");
	}

}
