package com.lanccj.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseService<M extends BaseService<M>> extends Model<M> implements IBean {

	public void setServiceId(Integer serviceId) {
		set("SERVICE_ID", serviceId);
	}

	public Integer getServiceId() {
		return get("SERVICE_ID");
	}

	public void setServiceName(String serviceName) {
		set("SERVICE_NAME", serviceName);
	}

	public String getServiceName() {
		return get("SERVICE_NAME");
	}

	public void setServiceClass(String serviceClass) {
		set("SERVICE_CLASS", serviceClass);
	}

	public String getServiceClass() {
		return get("SERVICE_CLASS");
	}

	public void setServiceMethod(String serviceMethod) {
		set("SERVICE_METHOD", serviceMethod);
	}

	public String getServiceMethod() {
		return get("SERVICE_METHOD");
	}

	public void setServiceDesc(String serviceDesc) {
		set("SERVICE_DESC", serviceDesc);
	}

	public String getServiceDesc() {
		return get("SERVICE_DESC");
	}

	public void setServiceUrl(String serviceUrl) {
		set("SERVICE_URL", serviceUrl);
	}

	public String getServiceUrl() {
		return get("SERVICE_URL");
	}

	public void setServiceCreateTime(java.util.Date serviceCreateTime) {
		set("SERVICE_CREATE_TIME", serviceCreateTime);
	}

	public java.util.Date getServiceCreateTime() {
		return get("SERVICE_CREATE_TIME");
	}

	public void setServiceCreater(String serviceCreater) {
		set("SERVICE_CREATER", serviceCreater);
	}

	public String getServiceCreater() {
		return get("SERVICE_CREATER");
	}

	public void setServiceApprovalTime(java.util.Date serviceApprovalTime) {
		set("SERVICE_APPROVAL_TIME", serviceApprovalTime);
	}

	public java.util.Date getServiceApprovalTime() {
		return get("SERVICE_APPROVAL_TIME");
	}

	public void setServiceApprover(String serviceApprover) {
		set("SERVICE_APPROVER", serviceApprover);
	}

	public String getServiceApprover() {
		return get("SERVICE_APPROVER");
	}

}
