package com.lanccj.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserId(Integer userId) {
		set("USER_ID", userId);
	}

	public Integer getUserId() {
		return get("USER_ID");
	}

	public void setUserName(String userName) {
		set("USER_NAME", userName);
	}

	public String getUserName() {
		return get("USER_NAME");
	}

	public void setUserPwd(String userPwd) {
		set("USER_PWD", userPwd);
	}

	public String getUserPwd() {
		return get("USER_PWD");
	}

	public void setUserNick(String userNick) {
		set("USER_NICK", userNick);
	}

	public String getUserNick() {
		return get("USER_NICK");
	}

	public void setUserPhone(String userPhone) {
		set("USER_PHONE", userPhone);
	}

	public String getUserPhone() {
		return get("USER_PHONE");
	}

}
