package com.lanccj.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseState<M extends BaseState<M>> extends Model<M> implements IBean {

	public void setStateId(Integer stateId) {
		set("STATE_ID", stateId);
	}

	public Integer getStateId() {
		return get("STATE_ID");
	}

	public void setStateMsg(String stateMsg) {
		set("STATE_MSG", stateMsg);
	}

	public String getStateMsg() {
		return get("STATE_MSG");
	}

}
