package com.lanccj.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public void setFModuleid(Integer fModuleid) {
		set("F_ModuleId", fModuleid);
	}

	public Integer getFModuleid() {
		return get("F_ModuleId");
	}

	public void setFParentid(Integer fParentid) {
		set("F_ParentId", fParentid);
	}

	public Integer getFParentid() {
		return get("F_ParentId");
	}

	public void setFEncode(String fEncode) {
		set("F_EnCode", fEncode);
	}

	public String getFEncode() {
		return get("F_EnCode");
	}

	public void setFFullname(String fFullname) {
		set("F_FullName", fFullname);
	}

	public String getFFullname() {
		return get("F_FullName");
	}

	public void setFIcon(String fIcon) {
		set("F_Icon", fIcon);
	}

	public String getFIcon() {
		return get("F_Icon");
	}

	public void setFUrladdress(String fUrladdress) {
		set("F_UrlAddress", fUrladdress);
	}

	public String getFUrladdress() {
		return get("F_UrlAddress");
	}

	public void setFTarget(String fTarget) {
		set("F_Target", fTarget);
	}

	public String getFTarget() {
		return get("F_Target");
	}

	public void setFIsmenu(String fIsmenu) {
		set("F_IsMenu", fIsmenu);
	}

	public String getFIsmenu() {
		return get("F_IsMenu");
	}

	public void setFAllowexpand(String fAllowexpand) {
		set("F_AllowExpand", fAllowexpand);
	}

	public String getFAllowexpand() {
		return get("F_AllowExpand");
	}

	public void setFIspublic(String fIspublic) {
		set("F_IsPublic", fIspublic);
	}

	public String getFIspublic() {
		return get("F_IsPublic");
	}

	public void setFAllowedit(String fAllowedit) {
		set("F_AllowEdit", fAllowedit);
	}

	public String getFAllowedit() {
		return get("F_AllowEdit");
	}

	public void setFAllowdelete(String fAllowdelete) {
		set("F_AllowDelete", fAllowdelete);
	}

	public String getFAllowdelete() {
		return get("F_AllowDelete");
	}

	public void setFSortcode(String fSortcode) {
		set("F_SortCode", fSortcode);
	}

	public String getFSortcode() {
		return get("F_SortCode");
	}

	public void setFDeletemark(String fDeletemark) {
		set("F_DeleteMark", fDeletemark);
	}

	public String getFDeletemark() {
		return get("F_DeleteMark");
	}

	public void setFEnabledmark(String fEnabledmark) {
		set("F_EnabledMark", fEnabledmark);
	}

	public String getFEnabledmark() {
		return get("F_EnabledMark");
	}

	public void setFDescription(String fDescription) {
		set("F_Description", fDescription);
	}

	public String getFDescription() {
		return get("F_Description");
	}

	public void setFCreatedate(java.util.Date fCreatedate) {
		set("F_CreateDate", fCreatedate);
	}

	public java.util.Date getFCreatedate() {
		return get("F_CreateDate");
	}

	public void setFCreateuserid(Integer fCreateuserid) {
		set("F_CreateUserId", fCreateuserid);
	}

	public Integer getFCreateuserid() {
		return get("F_CreateUserId");
	}

	public void setFCreateusername(String fCreateusername) {
		set("F_CreateUserName", fCreateusername);
	}

	public String getFCreateusername() {
		return get("F_CreateUserName");
	}

	public void setFModifydate(java.util.Date fModifydate) {
		set("F_ModifyDate", fModifydate);
	}

	public java.util.Date getFModifydate() {
		return get("F_ModifyDate");
	}

	public void setFModifyuserid(Integer fModifyuserid) {
		set("F_ModifyUserId", fModifyuserid);
	}

	public Integer getFModifyuserid() {
		return get("F_ModifyUserId");
	}

	public void setFModifyusername(String fModifyusername) {
		set("F_ModifyUserName", fModifyusername);
	}

	public String getFModifyusername() {
		return get("F_ModifyUserName");
	}

}
