package com.lanccj.manage.model;

import com.lanccj.manage.model.base.BaseService;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Service extends BaseService<Service> {
	public static final Service dao = new Service();
}
