package com.lanccj.manage.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("menu", "F_ModuleId", Menu.class);
		arp.addMapping("service", "SERVICE_ID", Service.class);
		arp.addMapping("state", "STATE_ID", State.class);
		arp.addMapping("user", "USER_ID", User.class);
	}
}

