package com.lanccj.manage.model;

import com.jfinal.plugin.activerecord.Page;
import com.lanccj.manage.model.base.BaseService;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Service extends BaseService<Service> {
	public static final Service dao = new Service();

	public Page<Service> paginate(Integer pageNumber, Integer pageSize,
			Service service) {
		String sql = "from service  where 1=1 ";
		return paginate(pageNumber, pageSize, "select *", sql);
	}
}
