package com.lanccj.manage.model;

import com.lanccj.manage.model.base.BaseState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class State extends BaseState<State> {
	public static final State dao = new State();
}
